//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{

    public partial class FAQ
    {

        /// <summary>
        /// pnlNoFAQs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoFAQs;

        /// <summary>
        /// rptFAQs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFAQs;
    }
}
