//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{

    public partial class Inquiry
    {

        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>
        /// litSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSuccess;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtSubject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSubject;

        /// <summary>
        /// txtMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMessage;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
