//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{

    public partial class Payment
    {

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// pnlAlreadyEnrolled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAlreadyEnrolled;

        /// <summary>
        /// pnlPayment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPayment;

        /// <summary>
        /// txtCardName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCardName;

        /// <summary>
        /// txtCardNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCardNumber;

        /// <summary>
        /// txtExpiry control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExpiry;

        /// <summary>
        /// txtCVV control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCVV;

        /// <summary>
        /// btnPay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPay;

        /// <summary>
        /// litCourseTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseTitle;

        /// <summary>
        /// litCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCategory;

        /// <summary>
        /// litDifficulty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDifficulty;

        /// <summary>
        /// litPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPrice;
    }
}
