//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{

    public partial class PaymentSuccess
    {

        /// <summary>
        /// litCourseName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseName;

        /// <summary>
        /// litCourseTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseTitle;

        /// <summary>
        /// litAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAmount;
    }
}
